Extract correct app module name (#506)
I was previously observing that the single_script_fastapi.py example
failed with

```
Container [fastapi-single-script]: ERROR:   File "/opt/venv/bin/fserve", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/venv/lib/python3.14/site-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.14/site-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.14/site-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.14/site-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
  File "/opt/venv/lib/python3.14/site-packages/flyte/_bin/serve.py", line 298, in main
    raise ValueError("--resolver and --resolver-args are required when using --tgz code bundle")
Filtered traceback (most recent call last):
ValueError: --resolver and --resolver-args are required when using --tgz code bundle
```

when running 

```
katrina in ~/src/flyte/flyte-sdk/examples/apps on single-script-streamlit ● λ flyte -vvv deploy single_script_fastapi.py env
```

with this fix, the app deploys successfully

---------

Signed-off-by: Katrina Rogan <katroganGH@gmail.com>